# Generated by Django 4.1.1 on 2022-11-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=50)),
                ('username', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('contact', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(upload_to='pictures/')),
                ('gender', models.TextField(max_length=50)),
            ],
        ),
    ]
